Admin/urls.py

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from .export import *
urlpatterns = [ 
  path('dashboard/',dashboard, name='admin_dashboard'), 

  path('user_list/',user_list, name='admin_user_list'), 
  path('update_user/<int:id>',update_user, name='admin_update_user'), 
  path('delete_user/<int:id>',delete_user, name='admin_delete_user'), 

  path('dealer_list/',dealer_list, name='admin_dealer_list'), 
  path('create_dealer/',create_dealer, name='admin_create_dealer'), 
  path('update_dealer/',update_dealer, name='admin_update_dealer'), 
  path('delete_dealer/<int:id>',delete_dealer, name='admin_delete_dealer'), 

  path('product_list/',product_list, name='admin_product_list'), 
  path('create_product/',create_product, name='admin_create_product'), 
  path('update_product/',update_product, name='admin_update_product'), 
  path('delete_product/<int:id>',delete_product, name='admin_delete_product'), 
  
  path('purchase_list/',purchase_list, name='admin_purchase_list'), 
  path('create_purchase/',create_purchase, name='admin_create_purchase'),
  # path('update_purchase/',update_purchase, name='admin_update_purchase'), 
  path('delete_purchase/<int:id>',delete_purchase, name='admin_delete_purchase'), 
  
  
  path('invoice_list/',invoice_list, name='admin_invoice_list'), 
  path('create_invoice/',create_invoice, name='admin_create_invoice'),
  path('update_invoice/',update_invoice, name='admin_update_invoice'), 
  path('delete_invoice/<int:id>',delete_invoice, name='admin_delete_invoice'), 
  path('add_invoice_in_account/<int:id>',add_invoice_in_account, name='admin_add_invoice_in_account'), 

  path('transaction_list/',transaction_list, name='admin_transaction_list'), 
  path('create_transaction/',create_transaction, name='admin_create_transaction'),
  path('update_transaction/',update_transaction, name='admin_update_transaction'), 
  path('delete_transaction/<int:id>',delete_transaction, name='admin_delete_transaction'), 
  path('print_transactions_receipt/<int:id>',print_transactions_receipt, name='admin_print_transactions_receipt'), 

  path('invoice_item_list/<int:id>',invoice_item_list, name='admin_invoice_item_list'), 
  path('delete_invoice_item/<int:id>',delete_invoice_item, name='admin_delete_invoice_item'), 
  path('get_product_details/',get_product_details, name='admin_get_product_details'), 

  path('dealer_bulk_creation/',dealer_bulk_creation, name='admin_dealer_bulk_creation'), 
  path('product_bulk_creation/',product_bulk_creation, name='admin_product_bulk_creation'), 

  path('print_all_invoice_formate/<int:id>',print_all_invoice_formate, name='admin_print_all_invoice_formate'), 
  path('troubleshoot_transactions_for_balance/',troubleshoot_transactions_for_balance, name='admin_troubleshoot_transactions_for_balance'), 


  path('export_invoice_list_pdf/',export_invoice_list_pdf, name='admin_export_invoice_list_pdf'), 
  path('export_invoice_list_csv/',export_invoice_list_csv, name='admin_export_invoice_list_csv'), 
  path('export_transaction_list_csv/',export_transaction_list_csv, name='admin_export_transaction_list_csv'), 
  path('export_transaction_list_pdf/',export_transaction_list_pdf, name='admin_export_transaction_list_pdf'), 
  path('export_stock_details_csv/',export_stock_details_csv, name='admin_export_stock_details_csv'), 

  # performa Invoice Links
  path('performa_invoice_list/',performa_invoice_list, name='admin_performa_invoice_list'), 
  path('create_performa_invoice/',create_performa_invoice, name='admin_create_performa_invoice'),  
  path('update_performa_invoice/',update_performa_invoice, name='admin_update_performa_invoice'), 
  path('delete_performa_invoice/<int:id>',delete_performa_invoice, name='admin_delete_performa_invoice'), 
  
  path('performa_invoice_item_list/<int:id>',performa_invoice_item_list, name='admin_performa_invoice_item_list'), 
  path('delete_performa_invoice_item/<int:id>',delete_performa_invoice_item, name='admin_delete_performa_invoice_item'), 
  path('print_performa_invoice/<int:id>',print_performa_invoice, name='admin_print_performa_invoice'), 

  path('add_extra_charges_in_invoice/',add_extra_charges_in_invoice, name='admin_add_extra_charges_in_invoice'),  

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DHARAMRAJ/urls.py
from django.contrib import admin
from django.urls import path,include
from Admin import urls as Admin_Urls
from Staff import urls as Staff_Urls
from Developer import urls as Developer_ERP_Urls

from Developer.views import login,logout
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('user/', include(User_ERP_Urls)),
    path('admin/', include(Admin_Urls)), 
    path('staff/', include(Staff_Urls)), 
    path('', Developer_ERP_Urls.index, name="index"),
    path('developer/', include(Developer_ERP_Urls)),
    path('accounts/login/',login, name='account_login'), 
    path('logout/',logout, name='logout'), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Developer/models.py
from django.db import models, transaction
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum

class CustomUser(AbstractUser):
    name = models.CharField( max_length=50)
    designation = models.CharField( max_length=50)
    is_admin=models.BooleanField(default=False)
    profile_image=models.ImageField(upload_to="prifile_images", max_length=500)
    def __str__(self):
        return self.username


GST_FOR_PRODUCT=(
    ("6","6"),
    ("12","12"),
    ("18","18"),
)


class State(models.Model):
    state_name=models.CharField(max_length=20)
    def __str__(self):
        return self.state_name

class Dealer(models.Model):
    dealer_name = models.CharField(max_length=40, db_index=True)
    business_name = models.CharField(max_length=40, db_index=True)
    mobile_no = models.CharField(max_length=12, db_index=True)
    email_id = models.CharField(max_length=40, db_index=True)
    address = models.CharField(max_length=200)
    state = models.ForeignKey(State, on_delete=models.CASCADE, db_index=True)
    pin_code = models.CharField(max_length=30,null=True, db_index=True)
    gst_number=models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.business_name

class Product(models.Model):
    product_code = models.CharField(max_length=20, unique=True, db_index=True)
    product_name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(null=True, blank=True)
    sale_amount=models.IntegerField(null=True)
    hsn_sac=models.IntegerField(null=True)
    minimum_stock=models.IntegerField(default=0)
    gst=models.CharField(max_length=50,choices=GST_FOR_PRODUCT,null=True)
    available_stock = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.product_name

class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    quantity = models.PositiveIntegerField()
    purchase_date = models.DateTimeField(auto_now_add=True, db_index=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.product.available_stock += self.quantity
        self.product.save()
    
    def __str__(self):
        return f"{self.quantity} {self.product} purchased on {self.purchase_date}"


from django.utils import timezone

class Invoice(models.Model):
    invoice_number = models.CharField(max_length=50, db_index=True)
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, db_index=True)
    invoice_date = models.DateField(db_index=True, auto_now_add=True, auto_now=False)
    total_gst_amount = models.IntegerField(null=True, blank=True)
    grand_total = models.IntegerField(null=True, blank=True)
    is_added_in_account=models.BooleanField(default=False)
    packing_charges = models.IntegerField(null=True, blank=True)
    transportation_charges = models.IntegerField(null=True, blank=True)
    is_original=models.BooleanField(default=True) 

    def __str__(self):
        return f"Invoice #{self.invoice_number} for {self.dealer}"
    
    # def save(self, *args, **kwargs):
    #     if not self.invoice_number:
    #         # Auto-generate invoice_number
    #         prefix = 'DHRMJ'

    #         # Find the highest existing invoice number for the current year
    #         last_invoice = Invoice.objects.select_related().order_by('-id').first()

    #         if last_invoice:
    #             last_number = int(last_invoice.invoice_number[-6:])
    #             next_invoice_number = last_number + 1
    #         else:
    #             next_invoice_number = 1
    #         # Set the new invoice number
    #         self.invoice_number = f'{prefix}{next_invoice_number:06d}' 
    #     super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        with transaction.atomic():
            # Iterate over related InvoiceItems and update associated product's available_stock
            for invoice_item in self.invoiceitem_set.all():
                product = invoice_item.product
                product.available_stock += invoice_item.quantity
                product.save()
            
            super().delete(*args, **kwargs)

class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, db_index=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    quantity = models.PositiveIntegerField()
    rate = models.IntegerField()
    gst_percent = models.FloatField()
    taxable_amount = models.IntegerField()
    gst_amount = models.IntegerField()
    total_amount = models.IntegerField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.product.available_stock -= self.quantity
        self.invoice.is_added_in_account=False
        self.product.save() 

        # Update GST amount in associated Invoice
        invoice_items = InvoiceItem.objects.filter(invoice=self.invoice)
        total_gst_amount = invoice_items.aggregate(total_gst_amount=Sum('gst_amount'))['total_gst_amount']
        self.invoice.total_gst_amount = total_gst_amount
        self.invoice.save()
        
        # Update grand total in associated Invoice
        grand_total = invoice_items.aggregate(total_total_amount=Sum('total_amount'))['total_total_amount']
        self.invoice.grand_total = grand_total 
        self.invoice.save()
    
    def __str__(self):
        return f"{self.quantity} {self.product}"
    
    def delete(self, *args, **kwargs):
        with transaction.atomic():
            product = self.product
            invoice = self.invoice
            product.available_stock += self.quantity
            invoice.grand_total -= self.total_amount
            invoice.total_gst_amount -= self.gst_amount
            product.save()
            invoice.save()
            super().delete(*args, **kwargs)

            invoice_items = InvoiceItem.objects.filter(invoice=self.invoice)
            grand_total = invoice_items.aggregate(total_total_amount=models.Sum('total_amount'))['total_total_amount']
            self.invoice.grand_total = grand_total
            self.invoice.is_added_in_account=False
            self.invoice.save()

PAYMENT_MODE = (
    ('Phone Pay', 'Phone Pay'),
    ('Credit Card', 'Credit Card'),
    ('Bank Transfer', 'Bank Transfer'),
    ('Cash', 'Cash'),
    ('Cheque', 'Cheque'),  
)

class Account(models.Model):
    transaction_id=models.CharField(unique=True,null=True, max_length=50)
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE, db_index=True)
    amount = models.IntegerField()
    payment_mode = models.CharField(max_length=50, choices=PAYMENT_MODE)
    transaction_date = models.DateTimeField(auto_now_add=True, db_index=True)
    is_credit=models.BooleanField(default=True)
    balance = models.IntegerField(default=0, null=True)
    remark = models.TextField(blank=True, null=True)
    invoice_number = models.CharField(max_length=50, blank=True, null=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='created_transactions')
    modified_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='modified_transactions')
     
    def save(self, *args, **kwargs):
        if not self.transaction_id:
            # Auto-generate transactio id
            prefix = 'TRDH'

            # Find the highest existing transaction id for the current year
            last_rec = Account.objects.select_related().order_by('-id').first()

            if last_rec:
                last_number = int(last_rec.transaction_id[-6:])
                next_transaction_number = last_number + 1
            else:
                next_transaction_number = 1
            # Set the new transaction id number
            self.transaction_id = f'{prefix}{next_transaction_number:06d}' 
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Transaction #{self.amount} {self.payment_mode}"


class PerformaInvoice(models.Model):
    performa_invoice_number = models.CharField(max_length=50, db_index=True, unique=True)
    party_name = models.CharField(max_length=50) 
    address = models.TextField()
    gst_number = models.CharField(max_length=20,null=True, blank=True)
    date = models.DateField(db_index=True, auto_now_add=True, auto_now=False)
    mobile=models.CharField(max_length=12)
    state=models.ForeignKey(State, on_delete=models.CASCADE, db_index=True)
    
    def __str__(self):
        return f"Invoice #{self.performa_invoice_number}"
 
    def save(self, *args, **kwargs):
        if not self.performa_invoice_number:
            # Auto-generate invoice_number
            prefix = 'PER-DH-'

            # Find the highest existing invoice number for the current year
            last_invoice = PerformaInvoice.objects.select_related().order_by('-id').first()

            if last_invoice:
                last_number = int(last_invoice.performa_invoice_number[-6:])
                next_invoice_number = last_number + 1
            else:
                next_invoice_number = 1
            # Set the new invoice number
            self.performa_invoice_number = f'{prefix}{next_invoice_number:06d}' 
        super().save(*args, **kwargs)
     
 
class PerformaInvoiceItem(models.Model):
    performa_invoice = models.ForeignKey(PerformaInvoice, on_delete=models.CASCADE, db_index=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    quantity = models.PositiveIntegerField()
    rate = models.IntegerField()
    gst_percent = models.FloatField()
    gst_amount = models.IntegerField(null=True)

Admin/templates/admin__performa_invoice_item.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block containt %}
<style>
    .model-card{
        border:2px solid gray;
        background:red;
        border-radius:10px;
         color:#fff;
    }  
  </style>
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-account"></i>
        </span>Performa Invoice Items
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class=" ">
                <span class=" bg-gradient-primary buttton " data-toggle="modal"
                data-target="#model_generate_bill" style="padding:10px; border-radius:6px;cursor: pointer;color:white;">Export / Print</span>
            </li>
        </ul>
    </nav>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="container">
        <div class="row">
        <div class="col-sm-6"><h4 class="alert alert-warning">Invoice No : {{invoice_details.performa_invoice_number}} </h4></div>
        <div class="col-sm-6"><h4 class="alert alert-warning">Party Name : {{invoice_details.party_name}} </h4></div>
    </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="row">
            <div class="container" style="max-width:90%;">
                <form method="POST" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-2">
                            <label for="id_product_code" class="form-label requiredField">
                                Search Product
                            </label>
                            <input type="text" name="product_code" oninput="get_details()" placeholder="Enter Product Code..." class="form-control" id="id_product_code">
                        </div>
                        <div class="col-sm-8">
                            {{form.product|as_crispy_field}}
                        </div> 
                        <div class="col-sm-2">
                            {{form.rate|as_crispy_field}}
                        </div>
                        <div class="col-sm-2">
                            {{form.quantity|as_crispy_field}}
                        </div>
                        <div class="col-sm-2">
                            {{form.gst_percent|as_crispy_field}}
                        </div>
                        <div class="col-sm-2">
                            {{form.taxable_amount|as_crispy_field}}
                        </div>
                        <div class="col-sm-3">
                            {{form.gst_amount|as_crispy_field}}
                        </div>
                        <div class="col-sm-3">
                            {{form.total_amount|as_crispy_field}}
                        </div> 
                    </div> 
                    <center> <input type="submit" value="Add" class="btn bg-gradient-primary text-light px-5 px-3">
                      
                    </center>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="model_generate_bill" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Print Bill</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"> 
                    <div class="row">
                        <div class="row">
                            <div class="col-md-3 mb-4">
                                <div class="model-card" style="background: linear-gradient(90deg, rgba(30,41,91,1) 0%, rgba(16,135,159,1) 100%);">
                                    <div class="card-body">
                                        <h5 class="card-title">No Of Products</h5>
                                        <hr>
                                        <h3>{{total_products}}</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 mb-4">
                                <div class="model-card" style="background: linear-gradient(90deg, rgba(64,30,91,1) 0%, rgba(159,16,146,1) 100%);">
                                    <div class="card-body">
                                        <h5 class="card-title">Total Quantity</h5>
                                        <hr>
                                        <h3>{{total_quantity}}</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 mb-4">
                                <div class="model-card" style="background: linear-gradient(90deg, rgba(64,30,91,1) 0%, rgba(159,16,146,1) 100%);">
                                    <div class="card-body">
                                        <h5 class="card-title">GST Amount</h5>
                                        <hr>
                                        <h3>{{total_gst_amount}}</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 mb-4">
                                <div class="model-card" style="background: linear-gradient(90deg, rgba(91,30,56,1) 0%, rgba(224,8,114,1) 100%);">
                                    <div class="card-body">
                                        <h5 class="card-title">Grand Total Amount</h5>
                                        <hr>
                                        <h3>{{grand_total_amount}}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <br><br>
                            <hr>
                            <div style="width:100%">
                                
                            <div class="alert alert-warning alert-dismissible">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                Printing is limited to a single occurrence. Once a print request is initiated, additional print requests are not permissible. Kindly take note of this limitation
                              </div>
                            </div>
                    <center>
                        <a href="{% url "admin_print_performa_invoice" id %}" class="btn bg-gradient-primary text-light px-5 px-3" style="width:300px">Generate and Print Bills</a>
                    </center>                     
                </div>
                
            </div> 
        </div>
    </div>
</div>

<div class="container mt-3" style=" overflow:scroll;">
    <table id="example" class="table table-striped " style="overflow:scroll; width:100%;min-width: max-content;">
        <thead>
            <tr class="bg-gradient-primary text-light ">
                <th scope="col" class="text-center text-white" style="">Sr.No</th>
                <th scope="col" class="text-center text-white" style="">Product</th> 
                <th scope="col" class="text-center text-white" style="">Basic Amount</th>
                <th scope="col" class="text-center text-white" style="">Quantity</th> 
                <th scope="col" class="text-center text-white" style="">GST %</th> 
                <th scope="col" class="text-center text-white" style="">GST Amount</th> 
                <th scope="col" class="text-center text-white" style="">Total Amount</th> 
                <th scope="col" class="text-center text-white" style="">Action</th> 
            </tr>
        </thead>
        <tbody id="invoice_table_body">
            {% if invoice_rec %}
            {% for r in invoice_rec %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{r.product}}</td> 
                <td class="text-center">{{r.rate}}</td>
                <td class="text-center">{{r.quantity}}</td>
                <td class="text-center">{{r.gst_percent}}</td>
                <td class="text-center">&#8377; {{r.gst_amount}}.00</td>
                <td class="text-center">&#8377; {{r.total_amount}}.00</td>
                <td>
                    <center>
                        <a href="{% url "admin_delete_performa_invoice_item" r.id %}" class="btn btn-danger px-3"><i class="mdi mdi-delete"></i></a>
                    </center>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td> 
                <td class="text-center"></td>
                <td class="text-center"></td>
                <td class="text-center"><b>Total</b></td>
                <td class="text-center"><b>&#8377; {{total_gst_amount}}.00</b></td>
                <td class="text-center"><b>&#8377; {{grand_total_amount}}.00</b></td>
                <td>   </td>
            </tr>
            {% else %}

            {% endif %}
        </tbody>
    </table>
</div>


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    function get_details() {
        var productCode = $('#id_product_code').val(); // Obtain the product code from the input field
        var productId = $('#id_product').val(); // Obtain the product code from the input field

        $.ajax({
            url: '/admin/get_product_details/',  // Replace with your actual endpoint
            data: {'product_code': productCode,'productId':productId},
            type: 'GET',
            success: function (data) {
                // Update form fields with the fetched details
                $('#id_product').val(data.product_name);
                $('#id_quantity').val(1);
                $('#id_rate').val(data.sale_amount);
                $('#id_gst_percent').val(data.gst);

                qty = 1;
                rate = parseFloat(data.sale_amount);
                gstPercent = parseFloat(data.gst);

                // Calculate GST amount and total amount
                var gstAmount = (rate * qty * gstPercent) / 100;
                var totalAmount = rate * qty + gstAmount;
                $('#id_taxable_amount').val(rate * qty);
                $('#id_gst_amount').val(parseInt(gstAmount));
                $('#id_total_amount').val(parseInt(totalAmount));
 
            },
            error: function (error) {
                console.log('Error:', error);
                
                $('#id_product').val();
                $('#id_quantity').val();
                $('#id_rate').val();
                $('#id_gst_percent').val();
                $('#id_taxable_amount').val();
                $('#id_gst_amount').val();
                $('#id_total_amount').val();
            }
        });
    }
 

    function generate_amount(){
        rate=document.getElementById('id_rate').value;
        qty=document.getElementById('id_quantity').value;
        gst_percent=document.getElementById('id_gst_percent').value;
        
        rate = parseFloat(rate);
        qty = parseFloat(qty);
        gstPercent = parseFloat(gst_percent);
                
        var gstAmount = (rate * qty * gstPercent) / 100;
        var totalAmount = rate * qty + gstAmount;

        $('#id_taxable_amount').val(rate * qty);
        $('#id_gst_amount').val(parseInt(gstAmount));
        $('#id_total_amount').val(parseInt(totalAmount));
        
    } 
</script>


 
{% endblock containt %}

Admin/templates/admin__update_user.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block containt %}
<style>
  
</style>
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-account"></i>
        </span> Update User
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb"> 
            <li class=" "> 
            </li>
        </ul>
    </nav>
</div>
 

<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="container" style="max-width:90%;">
                <div>
                    <form action="" method="POST"  enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row"> 
                            <div class="col-sm-4">
                                {{form.name|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.designation|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{form.profile_image|as_crispy_field}}
                            </div> 
                            <div class="col-sm-6">
                                {{form.password1|as_crispy_field}}
                            </div>
                            <div class="col-sm-6">
                                {{form.password2|as_crispy_field}}
                            </div>
                        </div>
                    <input type="submit" value="Submit"  class="btn bg-gradient-primary text-light mt-3">
                    </center>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>


   
{% endblock containt %}